
CREATE TABLE users (
  username VARCHAR(25) PRIMARY KEY,
  password TEXT NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE requests (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  response TEXT,
  username VARCHAR(25) NOT NULL
    REFERENCES users ON DELETE CASCADE
);

